services:
  - type: web
    name: medical-device-classifier
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn example:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: PORT
        value: 10000 